# Generated by Django 5.0.3 on 2024-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=400)),
                ('servicio', models.CharField(max_length=700)),
                ('comentarios_extras', models.CharField(default=' ', max_length=300)),
                ('link', models.CharField(max_length=500)),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago', models.CharField(max_length=200)),
                ('confirmacion_pago', models.CharField(max_length=200)),
                ('confirmacion_servicio', models.CharField(default='No confirmado', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('numero_celular', models.BigIntegerField()),
                ('correo_electronico', models.CharField(max_length=500)),
                ('contrasena', models.CharField(max_length=300)),
                ('rol', models.IntegerField()),
                ('creditos', models.FloatField()),
            ],
        ),
    ]
