# Generated by Django 5.0.3 on 2024-03-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioservicio',
            name='numero_celular',
        ),
    ]
