# Generated by Django 5.0.3 on 2024-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_servicios', '0003_usuarioservicio_last_login_usuarioservicio_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioservicio',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='usuarioservicio',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
