# Generated by Django 5.0.3 on 2024-03-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_servicios', '0008_remove_cryptopayment_amount_cryptopayment_btc_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptopayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cryptopayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='tx_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='btc_amount',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
