# Generated by Django 5.0.3 on 2024-03-30 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_servicios', '0009_remove_cryptopayment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptopayment',
            name='tx_id',
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='btc_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='currency',
            field=models.CharField(default='BTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
