# Generated by Django 5.0.3 on 2024-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_servicios', '0010_remove_cryptopayment_tx_id_cryptopayment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=400)),
                ('servicio', models.CharField(max_length=700)),
                ('comentarios_extras', models.CharField(default=' ', max_length=300)),
                ('link', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='supervisortabla',
            name='confirmacion_pago',
            field=models.CharField(default='No confirmado', max_length=200),
        ),
    ]
